// Авторизация
export const SET_USER_DATA = 'SET_USER_DATA';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

// Сотрудники
export const DOCUMENTS_GET_REQUEST = 'DOCUMENTS_GET_REQUEST';
export const DOCUMENTS_GET_SUCCESS = 'DOCUMENTS_GET_SUCCESS';
export const DOCUMENTS_GET_ERROR = 'DOCUMENTS_GET_ERROR';
